# Generated by Django 2.1 on 2018-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provisioningstatus',
            fields=[
                ('pkid', models.AutoField(primary_key=True, serialize=False)),
                ('intent', models.CharField(max_length=2000)),
                ('submittime', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
