# Generated by Django 2.1 on 2018-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentengine', '0003_provisioningstatus_provisiontaskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioningstatus',
            name='submittime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
